#!/bin/bash
#
# gen_slaves -n <num_slaves>
#
# print a new $SPARK_CONFIG_DIR/slaves with <num_slaves> in it
#
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Sat 25 Apr 2015 11:09:40 AM EDT
# Last Modified: Mon 27 Apr 2015 03:17:45 PM EDT
# =================================================

. spark_vars
NUM_ASSIGNED_NODES=6

slave_file="$SPARK_CONFIG_DIR/slaves"
if [ -r "$slave_file" ]; then
	num_nodes=$(wc -l < "$slave_file")
else
	num_nodes=0
fi

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

print_all_slaves() {
	cat <<EOF
himrod-7
himrod-8
himrod-9
himrod-16
himrod-17
himrod-18
himrod-19
himrod-20
himrod-21
himrod-1
himrod-2
himrod-3
himrod-4
himrod-5
himrod-6
himrod-10
himrod-11
himrod-12
himrod-13
himrod-14
himrod-15
himrod-big-1
himrod-big-2
himrod-big-3
himrod-big-4
EOF
}

optstring="in:f"
while getopts "$optstring" opt; do
	case "$opt" in
		i)
			in_place="true"
			;;
		n)
			num_nodes="$OPTARG"
			;;
		f)
			force="true"
			;;
		:)
			error "-$opt requires argument" 
			exit 1
			;; 
		?)
			error invalid option
			exit 1
			;; 
	esac
done

if (($# == 0)); then
	disp_opts -h -n 10 $0 2>/dev/null
	exit 0
fi

if [ -z "$num_nodes" ] || ((num_nodes < 1)); then
	error "-n $num_nodes is invalid"
	exit 1
fi

if ((num_nodes > $NUM_ASSIGNED_NODES)) && [ -z "$force" ]; then
	error "$num_nodes > NUM_ASSIGNED_NODES=$NUM_ASSIGNED_NODES; use -f flag to force this"
	error "Are you sure you've booked the nodes?"
	exit 1
fi

if [ -n "$in_place" ]; then
	file="$SPARK_CONFIG_DIR/slaves"

	# clobber current slaves file
	if [ -f "$file" ] && [ -r "$file" ]; then
		print_all_slaves | head -n $num_nodes > "$file"
		exit 0
	else
		error "$file is not a valid file"
		exit 1
	fi
fi
print_all_slaves | head -n $num_nodes
exit 0
