#!/bin/bash
# get the metrics per iteration

. spark_vars

optstring="1:2:m:s:d:"
while getopts $optstring opt
do
	case $opt in
		d)
			outputdir="$OPTARG"
			;;
		s)
			suffix="$OPTARG"
			;;
		m)
			metrics="$OPTARG"
			;;
		1)
			t1="$OPTARG"
			;;
		2) 
			t2="$OPTARG"
			;;
		?)
			echo "invalid option -$opt" 1>&2
			;;
		:)
			echo "-$opt requires argument"
			exit 1
			;;
	esac
done

shift $((OPTIND-1))

if [ -z "$metrics" ]; then
	metrics="$GANGLIA_METRICS"
fi

if [ -z "$suffix" ]; then
	suffix="-fil"
fi


# loop over all given directories
for d in "$@"; do
	if [ -d "$d" ]; then

		if [ -z "$t1" ] || [ -z "$t2" ]; then
			echo "Warning: specified times are invalid:" 1>&2
			echo "-1 $t1 -2 $t2" 1>&2
			continue
		fi

		if [ -z "$outputdir" ]; then
			outputdir="$d"
		fi

		for m in $metrics; do
			if [ -r "$d/$m" ]; then
				fout="$outputdir/$m$suffix"
				rrd_filter_time -1 $t1 -2 $t2 $d/$m > $fout
			else
				echo "Warning: $d/$m is not readable" 1>&2
			fi
		done

	else
		echo "$d is not a valid directory" 1>&2
	fi
done
