#!/bin/bash
#
# spark_link_conf [-d srcSparkConfDir] [destSparkConfDir]
# 
# Make symlinks in <destSparkConfDir> to the
# configuration files specified in <srcSparkConfDir>, if they exist.
#
# Ex:
# spark_link_conf -d ~/.spark ~/src/spark-1.5/conf
#
# The files must be identically named for the symlink to
# be created.
#
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Sun 15 Feb 2015 03:11:16 PM EST
# Last Modified: Tue 21 Jul 2015 07:26:53 PM EDT
# =================================================

srcdir=""

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

optstring="d:"
while getopts "$optstring" opt; do
	case "$opt" in
		d)
			srcdir="$OPTARG"
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if (($# == 0)); then
	disp_opts -h -n 12 $0 2>/dev/null
	exit 1
fi

if [ -z "$srcdir" ]; then
	error "-d srcdir unspecfied"
	exit 1
fi

if [ ! -d "$srcdir" ]; then
	error "-d $srcdir is not a valid directory"
	exit 1
fi

for d in "$@"; do
	if [ ! -d "$d" ]; then
		error "Not a valid directory: \"$d\""
		continue
	fi

	msg "Linking all configuration files in $srcdir to $d"
	for f in $(ls $srcdir); do
		if [ -r "$srcdir/$f" ]; then
			msg "$f ..."
			ln -rs "$srcdir/$f" "$d/" 2>/dev/null
		fi
	done

done
