#!/bin/bash
# 
# spark_start_nodes -n <num_nodes>
#
# Quick script to run with only a specified number of nodes
#
# This script will run head -n <num_nodes> on $SPARK_CONFIG_DIR/slaves,
# and truncate it to fewer nodes.
#
# The original file backuped up and then copied to its original form.
#
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Sat 18 Apr 2015 06:49:30 PM EDT
# Last Modified: Mon 27 Apr 2015 03:20:03 PM EDT
# =================================================

. spark_vars

if [ -r "$slave_file" ]; then
	num_nodes=$(wc -l < "$slave_file")
else
	num_nodes=0
fi

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}


optstring="Mn:s:"
while getopts "$optstring" opt; do
	case "$opt" in
		M)
			restart_master="true"
			;;
		s)
			sleep_time="$OPTARG"
			;;
		n)
			num_nodes="$OPTARG"
			;;
		:)
			error "-$opt requires argument" 
			exit 1
			;; 
		?)
			error invalid option
			exit 1
			;; 
	esac
done

if (($# == 0)); then
	disp_opts -h -n 10 $0 2>/dev/null
	exit 0
fi

if ((num_nodes > 0)); then

	# stop all the nodes + restart the master
	if [ -n "$restart_master" ]; then
		stop-all.sh
	else
		stop-slaves.sh
	fi
else
	error "You can't run with 0 nodes, stooopid."
	exit 1
fi

gen_slaves -i -f -n $num_nodes

# clean out the checkpoint dir
rm -r $SPARK_CHECKPOINT_DIR/*
cleartmp_all 2>&1 >/dev/null

if [ -n "$restart_master" ]; then
	start-all.sh
else
	start-slaves.sh
fi

if [ -n "$sleep_time" ]; then
	sleep "$sleep_time"
fi
